# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-17 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='product',
            field=models.ManyToManyField(to='app01.Menu'),
        ),
    ]
