# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-17 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20191017_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orderitem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='餐點數量')),
                ('info', models.CharField(blank=True, max_length=255, null=True, verbose_name='餐點備註')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Menu')),
            ],
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='info',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='ordermune',
            field=models.ManyToManyField(to='app01.Orderitem'),
        ),
    ]
